### ISSUE TITLE
Error when SIP service invoked

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/dionaea#34]
```
dionaea_1  | [10062019 20:22:55] python /code/modules/python/module.c:1061: 	 __init__
dionaea_1  | [10062019 20:22:55] root (unknown file):0: There was an error in the Python service
dionaea_1  | Traceback (most recent call last):
dionaea_1  |   File "binding.pyx", line 787, in dionaea.core.handle_io_in_cb
dionaea_1  |   File "lib/dionaea/python/dionaea/sip/__init__.py", line 655, in handle_io_in
dionaea_1  |     msg.set_personality(self.personality)
dionaea_1  | AttributeError: 'SipSession' object has no attribute 'personality'
```

**Comment by JesseBowling** [comment]
This was an upstream issue.
